version: 0.0

os: linux


hooks:
  ApplicationStop:
    - location: scripts/stop-process.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: scripts/start-process.sh
      timeout: 180
      runas: root